### ISSUE TITLE
Not hooking up to existing REST API

### ISSUE THREAD

**Issue by SaadBazaz** [27medkamal/djangorestframework-fsm#5]
Hey there, 
I've made some transitions in a data model called "Article". But when I try to integrate it in an existing REST API I've constructed for Article, it does not show up in Swagger. Here is what I do:
```
from rest_framework import generics, mixins
from djangorestframework_fsm.viewset_mixins import get_drf_fsm_mixin
from .models import Article

class ArticleAPIView (
        get_drf_fsm_mixin(Article, fieldname='status'),
        mixins.UpdateModelMixin,
        generics.RetrieveAPIView,    
    ):

   // . . .
```

If I add the viewset, as show below:
```
from rest_framework import generics, mixins
from djangorestframework_fsm.viewset_mixins import get_drf_fsm_mixin
from .models import Article
from rest_framework import viewsets

class ArticleAPIView (
        get_drf_fsm_mixin(Article, fieldname='status'),
        mixins.UpdateModelMixin,
        generics.RetrieveAPIView,    
        viewsets.ModelViewSet,
    ):
```
it throws the following error: ```TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, UpdateModelMixin, RetrieveAPIView, ModelViewSet```

How do I integrate this properly?

P.S.: The order of the generics and mixins is not making a difference.

**Comment by 27medkamal** [comment]
The issue above is not an issue in this library. You're using DRF's mixins incorrectly.

To give you an idea of the correct usage, here is the corrected second example (which you can also find in the docs):

```
from rest_framework import generics, mixins
from djangorestframework_fsm.viewset_mixins import get_drf_fsm_mixin
from .models import Article
from rest_framework import viewsets

class ArticleAPIView (
        get_drf_fsm_mixin(Article, fieldname='status'),
        viewsets.ModelViewSet,
    ):

```
